const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),http=require('http');
process.chdir(path.resolve(__dirname,'..'));
const server=http.createServer((req,res)=>{try{const f=path.join(process.cwd(),new URL(req.url,'http://local').pathname);res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f))}catch(e){res.writeHead(404);res.end()}});
(async()=>{await new Promise(r=>server.listen(8125,'127.0.0.1',r));const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'no-preference'});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();if(u.hostname==='api.themoviedb.org'){requests.push(u.pathname+'?'+u.searchParams);return r.fulfill({json:{results:[{id:101,name:'Test series',title:'Test movie',vote_average:8,vote_count:500,poster_path:'/a.jpg'},{id:102,name:'Second title',title:'Second movie',vote_average:8,vote_count:500,poster_path:'/b.jpg'}],page:1,total_pages:1}})}if(u.hostname==='image.tmdb.org')return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="600"><rect width="400" height="600" fill="#754690"/><circle cx="210" cy="220" r="140" fill="#498a88"/></svg>'});return r.abort()});
 fs.mkdirSync('qa',{recursive:true});
 for(const [file,count] of [['movies',10],['series',8]]){
  await page.goto('http://127.0.0.1:8125/'+file+'.html');await page.waitForSelector('#grid .card');await page.locator('#menu').click();
  assert.equal(await page.locator('#sidebar [data-category]').count(),count);
  assert(await page.locator('#sideClose').isVisible());await page.waitForFunction(()=>Math.abs(document.querySelector('#sidebar').getBoundingClientRect().left)<1);assert(await page.evaluate(()=>document.elementFromPoint(50,45).closest('#sidebar')!==null),'drawer must cover the header');
  await page.screenshot({animations:'disabled',path:'qa/v11-'+file+'-drawer.png'});
  const cats=await page.locator('#sidebar [data-category]').evaluateAll(es=>es.map(e=>e.dataset.category));
  for(const cat of cats){if(!(await page.locator('#sidebar').getAttribute('class')).includes('open'))await page.locator('#menu').click();await page.locator('#sidebar [data-category]').filter({hasText:cat}).first().click();await page.waitForSelector('#grid .card');assert.equal(await page.locator('#title').innerText(),cat);assert(!(await page.locator('#sidebar').getAttribute('class')).includes('open'));}
 }
 assert(requests.some(x=>x.includes('/discover/tv?')&&x.includes('with_genres=80')),'TV genre request must reach API');
 await page.locator('#themeTopControl').click();await page.locator('[data-mode="light"]').click();assert.equal(await page.locator('html').getAttribute('data-color-mode'),'light');
 await page.locator('[data-mode="system"]').click();await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.colorMode==='dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.colorMode==='light');
 await page.locator('[data-mode="dark"]').click();await page.locator('[data-appearance="glass"]').check();await page.locator('[data-appearance="mesh"]').check();await page.locator('[data-appearance="fullArt"]').check();
 await page.locator('[data-appearance="reduceMotion"]').check();assert.equal(await page.evaluate(()=>heroTimer&&allowArtworkMotion()),false);assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e,'::before').animationName),'none');
 await page.locator('[data-appearance="reduceBlur"]').check();assert.equal(await page.locator('.bottom-nav').evaluate(e=>getComputedStyle(e).backdropFilter),'none');
 await page.screenshot({animations:'disabled',path:'qa/v11-appearance-dark.png',fullPage:false});
 await page.locator('[data-appearance="reduceBlur"]').uncheck();await page.locator('[data-appearance="reduceMotion"]').uncheck();await page.locator('[data-appearance="artMotion"]').uncheck();assert.equal(await page.evaluate(()=>allowArtworkMotion()),false);
 await page.locator('#themeClose').click();assert.equal(await page.locator('.hero').evaluate(e=>getComputedStyle(e).borderRadius),'0px');assert((await page.locator('.bottom-nav').evaluate(e=>getComputedStyle(e).backdropFilter)).includes('blur'));
 assert.equal(await page.locator('.topbar #search').count(),0);await page.reload();await page.waitForSelector('#grid .card');assert.equal(await page.locator('html').getAttribute('data-glass'),'true');assert.equal(await page.evaluate(()=>appearance.artMotion),false);
 for(const size of [{width:390,height:844},{width:844,height:390},{width:1280,height:800}]){await page.setViewportSize(size);await page.screenshot({animations:'disabled',path:`qa/v11-glass-${size.width}.png`});assert(await page.locator('.bottom-nav a').evaluateAll(es=>es.every(e=>e.scrollHeight<=e.clientHeight+1)));await page.locator('#menu').click();assert(await page.locator('#sideClose').isVisible());await page.locator('#sideClose').click();}
 await page.setViewportSize({width:390,height:844});await page.locator('#themeTopControl').click();await page.locator('[data-mode="light"]').click();await page.waitForFunction(()=>document.querySelector('[data-mode="light"]').getAttribute('aria-pressed')==='true');await page.screenshot({animations:'disabled',path:'qa/v11-appearance-light.png'});await page.locator('#appearanceReset').click();assert.equal(await page.locator('html').getAttribute('data-glass'),'false');assert.equal(await page.locator('html').getAttribute('data-color-mode'),'dark');assert.deepEqual(errors,[]);
 console.log('PASS: sidebar above header, all movie/TV categories clickable and rendered, TV genre API requests, light/dark/system changes, glass and solid fallback, reduced motion, artwork sizing/rotation, persistence, reset and three viewport layouts.');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
