const {chromium}=require('playwright'),fs=require('fs'),http=require('http');
const hosts=new Set(fs.readFileSync('ad-hosts.txt','utf8').split('\n').filter(s=>s&&!s.startsWith('#')).map(s=>s.trim().split(/\s+/)).map(a=>a.length>1?a[1]:a[0]));
function blocked(h){while(h){if(hosts.has(h))return true;const i=h.indexOf('.');if(i<0)break;h=h.slice(i+1)}return false}
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<html><body style="margin:0;background:black"><iframe id="player" referrerpolicy="no-referrer" style="width:960px;height:540px;border:0" allow="autoplay;fullscreen;encrypted-media" sandbox="allow-scripts allow-same-origin allow-presentation allow-orientation-lock"></iframe></body></html>')});
(async()=>{await new Promise(r=>server.listen(8126,'127.0.0.1',r));fs.mkdirSync('qa-live',{recursive:true});const b=await chromium.launch();const report=[];
for(const [name,url] of [['ezvid-tv','https://ezvidapi.com/embed/tv/1399/1/2'],['ezvid-movie','https://ezvidapi.com/embed/movie/1726'],['vidcore-movie','https://vidcore.io/movie/1726?autoPlay=false']]){
 const c=await b.newContext({viewport:{width:980,height:600},serviceWorkers:'block'});await c.addInitScript({content:'window.__MS_TOKEN="candidate-test";'+fs.readFileSync('js/player-guard.js','utf8')});const p=await c.newPage();const row={name,url,blocked:[],popups:0,errors:[]};c.on('page',x=>{row.popups++;x.close().catch(()=>{})});
 await c.route('**/*',r=>{const u=new URL(r.request().url());if(blocked(u.hostname)){row.blocked.push(u.hostname);return r.abort()}return r.continue()});
 try{await p.goto('http://127.0.0.1:8126');const start=Date.now();await p.locator('#player').evaluate((f,u)=>f.src=u,url);await p.waitForTimeout(9000);row.frames=p.frames().map(f=>f.url());row.text=[];
 for(const f of p.frames().slice(1)){const txt=(await f.locator('body').innerText({timeout:3000}).catch(()=>'' )).slice(0,4000);row.text.push(txt);if(!/cloudflare|verify you are human|security verification|captcha/i.test(txt)){const play=f.getByRole('button',{name:/^(play|play video|start watching|watch now)$/i}).first();if(await play.count())await play.click({timeout:2500}).catch(()=>{});else if(name.startsWith('vidsrc')){const a=f.locator('#pl_but,#play_button,.play-button').first();if(await a.count())await a.click({timeout:2500}).catch(()=>{})}}}
 await p.waitForTimeout(10000);row.elapsedMs=Date.now()-start;row.after=[];for(const f of p.frames().slice(1)){row.after.push({url:f.url(),text:(await f.locator('body').innerText({timeout:3000}).catch(()=>'' )).slice(0,3000),videos:await f.locator('video').evaluateAll(vs=>vs.map(v=>({time:v.currentTime,ready:v.readyState,paused:v.paused,duration:Number.isFinite(v.duration)?v.duration:null,error:v.error?.code||null}))).catch(()=>[])});}await p.screenshot({path:'qa-live/'+name+'.png'});
 }catch(e){row.errors.push(e.message)}report.push(row);await c.close();}
 await b.close();server.close();fs.writeFileSync('qa-live/candidates.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
